//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public bool Completed { get; set; }
    }
}
